export const COMMAND_HELP_LINES = [
  'Commands:',
  '/help',
  '  Show all available slash commands and what they do.',
  '/provider',
  '  Choose a provider, then use it, add/remove models, set API key, or remove it.',
  '/model',
  '  Choose a model from all configured providers.',
  '/model <name-or-provider:name>',
  '  Set a model directly. Selecting a model also sets its provider.',
  '/settings',
  '  Show the configured provider, model, API key status, LSP/MCP servers, skills, and loaded context files.',
  '/settings open',
  '  Open ~/.haze/settings.json with the OS default app.',
  '/skills',
  '  Manage Markdown skills: generate a custom skill, show info, enable/disable, validate, or remove.',
  '/init',
  '  Inspect the current workspace and create or update AGENTS.md project instructions.',
  '/context',
  '  Show a token breakdown of the current request: system prompt, project context, tools (incl. MCP), and chat messages.',
  '/session',
  '  Show the current durable session file.',
  '/resume',
  '  Resume the latest saved session for this workspace.',
  '/new',
  '  Start a fresh durable session.',
  '/logs',
  '  List recent log files with sizes and dates.',
  '/lsp',
  '  Configure Language Server Protocol navigation tools (interactive picker).',
  '/mcp',
  '  Configure Model Context Protocol servers like Context7 (interactive picker).',
  '/logs <id>',
  '  Show summary of a specific log: entry counts by type, total tokens, tool calls.',
  '/compact [instructions]',
  '  Summarize older model context and keep recent messages.',
  '/clear',
  '  Clear the current chat conversation history.',
  '/exit',
  '  Exit Haze.',
  '/quit',
  '  Exit Haze.',
] as const;

export function formatCommandHelp(): string {
  return COMMAND_HELP_LINES.join('\n');
}
